### ISSUE TITLE
Deprecated API Usage in RxCocoa

### ISSUE THREAD

**Issue by jstngoulet** [RxSwiftCommunity/RxKeyboard#100]
RxCocoa should should be updated to 5.1 as UIWebview is being deprecated by apple.

**Comment by jdisho** [comment]
Hey @jstngoulet, `RxKeyboard` is supporting `RxSwift` 5.0 and above. Try running `pod update`.
https://github.com/RxSwiftCommunity/RxKeyboard/blob/5398ec417e2ad938c5f5db702b0b13df0c3702d4/RxKeyboard.podspec#L15
