### ISSUE TITLE
I cannot trigger this if the tableView content is less than the keyboard height.

### ISSUE THREAD

**Issue by JordanRoPo** [RxSwiftCommunity/RxKeyboard#19]
My app has a pull down view that turns off the bounce for my UITableView once the contentOffset.y  reaches 0 in order to create a seamless pull down pan gesture. Now the problem is, this works great when the content of the UITableView is interfered with the keyboard height, meaning the UITableView is still scrollable. However, if the content is not, then what happens is the view still swipes down, but the keyboard is stagnant. So I want to be able to trigger this manually incase the user wants to solely close the keyboard and not the view. How can I do this?

**Comment by devxoul** [comment]
@JordanRoPo I'm afraid I'm not sure the exact problem 😭 Can you please add some images or something else for me? Thanks!

**Comment by JordanRoPo** [comment]
@devxoul A great example would be within the iPhone music app. Whenever you go to a songs details while listening to a song, you can scroll down to see what songs are going to be played next or get the lyrics to the current song to show, if you continue pulling down, eventually the UITableView will have a contentOffset of 0. Once you pull down further, the UIView(or w/e it is) will slowly move down with your finger. So the problem I'm facing is if, for example, there was only a label, then the UITableView content height would prevent the embedded UITableView from "vertically bouncing". Without this vertical bounce and without a contentHeight that is not affected by the keyboard, and I try to swipe down, the keyboard doesn't move with my finger. So I'm trying to figure out how to move the keyboard using the position of the finger swipe, rather than relying on the keyboard notification. I'm sorry i cannot post any photos due to the app being proprietary ):

**Comment by devxoul** [comment]
@JordanRoPo Is this what you're facing? 🤔

* **What you expected**:

    > I hope the keyboard moves down along with the finger

* **The problem**:

    > Keyboard doesn't move down along with the finger

    ![rxkeyboard](https://cloud.githubusercontent.com/assets/931655/24343829/72feb598-1303-11e7-8f28-5ad1df3f4613.png)

**Comment by brunomunizaf** [comment]
Can we re-open this? I'm about to implement the same.
