### ISSUE TITLE
adapt to the updated RxCocoa

### ISSUE THREAD

**Issue by tomisacat** [RxSwiftCommunity/RxKeyboard#24]
Due to the API change of `RxCocoa`, some method has been deprecated and replaced like this:

>https://github.com/RxSwiftCommunity/RxKeyboard/blob/master/Sources/RxKeyboard.swift#L107

The `bindTo` method has been renamed to `bind(to)`, please update to adapt to the latest version of `RxCocoa`. Appreciate : )

**Comment by devxoul** [comment]
Hi @tomisacat, there's a pull request for this issue. If you'd like to dismiss warnings from CocoaPods, just add `inhibit_all_warnings!` to your Podfile.

```
platform :ios, '8.0'
inhibit_all_warnings!

target ...
```

**Comment by tomisacat** [comment]
Alright, good to hear your response and I'll do it.

Appreciate!
