### ISSUE TITLE
Should not list Carthage in Framework Search Paths

### ISSUE THREAD

**Issue by brentleyjones** [RxSwiftCommunity/RxKeyboard#25]
Currently `FRAMEWORK_SEARCH_PATHS ` is set to `$(PROJECT_DIR)/Carthage/Build/iOS`. This gives a warning when building from source in a consuming workspace:

```
ld: warning: directory not found for option '-F/Users/bejones/Development/project/Carthage/Checkouts/RxKeyboard/Carthage/Build/iOS'
```

The correct setup is to not have this and to include RxSwift in the Workspace and use Xcode's Implicit Dependency Management. That way it knows how to compile both as a part of Carthage and in the workspace for development: https://www.quora.com/How-should-an-OSS-library-be-structured-for-distribution-with-both-Carthage-and-CocoaPods/answer/Justin-Spahr-Summers

**Comment by brentleyjones** [comment]
Do we agree that this should/can be fixed? It's our last warning in our codebase currently.

**Comment by devxoul** [comment]
Oh sorry, I totally forgot about it. :pray: Could you please create a PR for this? I'm not experienced with Carthage.

**Comment by brentleyjones** [comment]
Sure, I'll try to get to it this week.

**Comment by freak4pc** [comment]
Uhm to be honest I wanted to fix this real quickly but I cannot reproduce your issue.

<img width="1397" alt="4881e98f-b820-456c-8783-41413f89c883" src="https://user-images.githubusercontent.com/605076/27871975-00a0da34-61b0-11e7-9ec1-a081862cb286.png">

**Comment by brentleyjones** [comment]
@freak4pc You need to build the project by including it in the workspace, not buy using `carthage` on the command line. We use `carthage` to manage the dependencies, but not to build it.

**Comment by freak4pc** [comment]
Could you provide a dummy project? I'm not sure which workspace you're referring to in that case :)

**Comment by brentleyjones** [comment]
In the image you have, you have `CarthageTest` as a project in a (probably implicit) workspace. Next to it you would drag in the `RxKeyboard` project. By including it in the same workspace it will be built with Xcode's Implicit Dependency Management (see link in original comment).

To provide an example project I would probably spend the couple more minutes and fix it, so it would be on the same timeline, sometime this week. Carthage itself uses this format though (https://github.com/Carthage/Carthage/blob/master/Carthage.xcworkspace/contents.xcworkspacedata) so you can see how they setup their workspace for an example.

**Comment by freak4pc** [comment]
Ok, not sure if I'm doing anything special here but - I did reproduce your issue, when dragging the product framework from RxKeyboard to my own project in the same workspace, it showed that message, but then I noticed that "Framework Search Path" was configured on my own project and not on RxKeyboard. When removing that line, I'm not seeing that warning again. 

Anyways if you're still experiencing it I'll leave it to you since I can't find an issue inside RxKeyboard itself :)
