### ISSUE TITLE
How to use for texfields in tableview

### ISSUE THREAD

**Issue by kmuddapu** [RxSwiftCommunity/RxKeyboard#29]
I have textfields in 3 sections in tableview . how to show  keyboard  near to textfield ?

Im using below code but when I click on bottom textfield . View going to top almost near to navigation.

```swift
RxKeyboard.instance.visibleHeight
            .drive(onNext: { keyboardVisibleHeight in
                self.view.setNeedsLayout()
                UIView.animate(withDuration: 0) {
                    self.myTableView.contentInset.bottom = keyboardVisibleHeight
                    self.myTableView.scrollIndicatorInsets.bottom  = self.myTableView.contentInset.bottom                    
                    self.view.layoutIfNeeded()
                }
            })
            .disposed(by: disposeBag)
```

**Comment by devxoul** [comment]
You should also adjust tableView's `contentOffset`.

**Comment by kmuddapu** [comment]
@devxoul Can you please provide me any sample code.

I wrote below code but not working . Tableview not scrolling to row selected.

 RxKeyboard.instance.willShowVisibleHeight
      .drive(onNext: { keyboardVisibleHeight in
        self. myTableView.contentOffset.y += keyboardVisibleHeight
      })
      .disposed(by: disposeBag)

**Comment by devxoul** [comment]
@kmuddapu try using `scrollToRowAtIndexPath` instead.
