### ISSUE TITLE
Carthage Build Failed

### ISSUE THREAD

**Issue by daidongon** [RxSwiftCommunity/RxKeyboard#38]
Log at Building Failed

```
Skipped building RxKeyboard due to the error:
Dependency "RxKeyboard" has no shared framework schemes for any of the platforms: iOS
```

**Comment by imairi** [comment]
+1

**Comment by imairi** [comment]
It seems not to support  `--no-use-binaries` option for Carthage.

**Comment by daidongon** [comment]
+1

**Comment by devxoul** [comment]
When do you need to use `--no-use-binaries`?

**Comment by daidongon** [comment]
In the Carthage build without the option `--no-use-binaries`, it crashed when launching the application.

- Build Condition
  - Xcode9 (9A235)
  - Carthage v0.25.0
  - `cartfile` is written that `github "RxSwiftCommunity/RxKeyboard"`

**Comment by devxoul** [comment]
@daidongon can you share the crash log?

**Comment by daidongon** [comment]
@devxoul 
<img width="839" alt="debug_launch_crash_log" src="https://user-images.githubusercontent.com/25152049/30958802-328a0bea-a479-11e7-9aa2-ea906e37dfcb.png">

- `cartfile` is written that `github "RxSwiftCommunity/RxKeyboard"`
- run script `carthage update --platform iOS RxKeyboard`
- After building completed, added to `Linked Frameworks and Libraries` and  `Input Files in Build Phases`
- Run Application on Xcode9
- Crash

**Comment by daidongon** [comment]
@devxoul 
Please check it out !

**Comment by devxoul** [comment]
@daidongon, thanks! I just replaced a prebuilt binary of 0.7.0, could you please try with it again?

**Comment by daidongon** [comment]
@devxoul 
I tried again in the same way and succeeded.
Thank you!!
