### ISSUE TITLE
New version not on Pods trunk

### ISSUE THREAD

**Issue by rynecheow** [RxSwiftCommunity/RxKeyboard#41]
Current version `0.7.0` one Cocoapods trunk is not in sync with the `master` branch where dependency for RxSwift version is different.

https://github.com/CocoaPods/Specs/tree/a0c2b84b032ad09150118e6b7bd4494b16efcf30/Specs/6/d/7/RxKeyboard

**Comment by devxoul** [comment]
I didn't release a new version because `>= 4.0.0-beta.0` contains `4.0.0`. Why do you need a new release?

**Comment by rynecheow** [comment]
Yes, and it is up to you.

But it is to keep anything less than the final release version away, as there are already multiple changes and bug fixes after `4.0.0-beta.0`.
