### ISSUE TITLE
Carthage update error

### ISSUE THREAD

**Issue by noppefoxwolf** [RxSwiftCommunity/RxKeyboard#42]
## Swift version
Apple Swift version 4.0 (swiftlang-900.0.65.2 clang-900.0.37)
Target: x86_64-apple-macosx10.9

## Carthage version
0.26.2

## Cartfile

```
github "RxSwiftCommunity/RxKeyboard" ~> 0.7
```

## console
`$carthage update --platform iOS`

## result
*** Skipped building RxKeyboard due to the error:
Dependency "RxKeyboard" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/RxSwiftCommunity/RxKeyboard/issues/new

**Comment by noppefoxwolf** [comment]
When use `--no-use-binaries` options, returned same result too.

**Comment by devxoul** [comment]
Carthage is supported from `0.7.0`. Can you use `~> 0.7` instead?

**Comment by noppefoxwolf** [comment]
Sorry, I fixed my post.
I have same issue on version 0.7.

**Comment by noppefoxwolf** [comment]
I made a PR that added a shared scheme.
If you need, please merge this.

https://github.com/RxSwiftCommunity/RxKeyboard/pull/43

**Comment by devxoul** [comment]
I think the actual error is:

```
*** Skipped installing RxSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65 clang-900.0.37)."
```

Let me check of it.

**Comment by devxoul** [comment]
@noppefoxwolf, I updated a prebuilt binary. could you please try again?

```console
$ rm -rf ~/Library/Caches/org.carthage.CarthageKit
$ carthage update --platform iOS
```

**Comment by noppefoxwolf** [comment]
It's worked!
Thank you for your nice work.
