### ISSUE TITLE
Suggestion for the next version.

### ISSUE THREAD

**Issue by DevAndArtist** [RxSwiftCommunity/RxKeyboard#46]
I don't use the framework, but I just happened to look over the code to learn about the interactive behaviour. I also tested the example application and quickly noticed a major issue.

Please check the events your keyboard wrapper is emitting on device rotations. For instance I edited the code to check if my assumption was right or wrong, because I bumped into similar problems  when observing the keyboard frame a couple a weeks ago.

```swift 
RxKeyboard.instance.isHidden
	.drive(onNext: { print("isHidden:", $0) })
	.disposed(by: disposeBag)
	
RxKeyboard.instance.visibleHeight
	.drive(onNext: { print($0) })
	.disposed(by: disposeBag)
```

The result looked something like this on an iPhone Plus - when the keyboard was visible and the device rotated.

```
// landscape to portrait
322.0
isHidden: true
0.0
isHidden: false
271.0
// portrait to landscape
-322.0
200.0
```

When rotating from the user perspective the keyboard is never hidden, it's just re-layouted. Furthermore the event with `271.0` is sent only *after* the rotation is done animating while there must be another frame change event before the device fully rotates. That's why if looking at the message bar in slow motion it will appear without animations on one of the rotations.

**Comment by devxoul** [comment]
@DevAndArtist thanks for reporting! I'll check this for the next release :+1:
