### ISSUE TITLE
Please add binary support for Xcode 9.2

### ISSUE THREAD

**Issue by bsarrazin** [RxSwiftCommunity/RxKeyboard#51]
The current release only supports Xcode 9.1
Please create a new release with Xcode 9.2 (swift 4.0.3) support.

**Comment by devxoul** [comment]
@bsarrazin, thanks for reporting! I just created [0.8.0 release](https://github.com/RxSwiftCommunity/RxKeyboard/releases/tag/0.8.0) and the prebuilt binary will be uploaded soon.

**Comment by devxoul** [comment]
Done!

**Comment by bsarrazin** [comment]
@devxoul please update the json file to point to the new binary.

**Comment by devxoul** [comment]
@bsarrazin, Done! I'll keep that in my mind :)

**Comment by bsarrazin** [comment]
Thank you @devxoul
