### ISSUE TITLE
Carthage binary for 0.8.1 is missing

### ISSUE THREAD

**Issue by akolov** [RxSwiftCommunity/RxKeyboard#53]
https://github.com/RxSwiftCommunity/RxKeyboard/releases/download/0.8.1/RxKeyboard.framework.zip leads to "Page not found"

**Comment by freak4pc** [comment]
@devxoul seems like the latest build doesn't have the RxKeyboard.framework.zip file attached: 

<img width="939" alt="ca693bbc-b76b-4eee-b5c1-361a3ee9ed71" src="https://user-images.githubusercontent.com/605076/34462613-4eb2c610-ee50-11e7-9a60-0a013ed8930b.png">

**Comment by freak4pc** [comment]
@akolov I've built and added the missing Prebuilt Binary. Should work fine now, closing this :)
