### ISSUE TITLE
Publish 0.8.1 to CocoaPods

### ISSUE THREAD

**Issue by nanoxd** [RxSwiftCommunity/RxKeyboard#54]
👋🏽,

I'm attempting to use the library and found that the last published version was 0.7.1. Any chance you could publish the latest version to CocoaPods? 

Thanks!

![](https://media3.giphy.com/media/26AHqztlb4CzG3WTu/giphy.gif?cid=348844935a53d267334c324c498fdf2e)

**Comment by devxoul** [comment]
Done! I have no idea why I forgot to upload it 🙀

**Comment by nanoxd** [comment]
Thanks!
