### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by igorkulman** [RxSwiftCommunity/RxKeyboard#58]
I tried integrating RxKeyboard to my project, but it did not work. So I downloaded you Example project, and it does not work either. When the `MessageListViewController` gets created the `RxKeyboard.instance.visibleHeight` is invoked with `0` and that is it, no other invocation when I focus the input and the keyboard comes up:

![mar-16-2018 20-07-36](https://user-images.githubusercontent.com/4746070/37540088-0f0bcca0-2956-11e8-9c52-25c7fd5d6db7.gif)

**Comment by devxoul** [comment]
It seems that #57 breaks the behavior. I've created #59 to fix it. I'd be glad if you could review it :)

**Comment by igorkulman** [comment]
I can confirm, works with #59

**Comment by devxoul** [comment]
@igorkulman, do you want me to make a new release? #57 was not released so 0.8.1 might work without #59.
