### ISSUE TITLE
Compatibility with Swift 4.1

### ISSUE THREAD

**Issue by Aurazion** [RxSwiftCommunity/RxKeyboard#60]
Hi,
I'm using Xcode 9.3 beta 4 with Swift 4.1 and carthage for my dependencies. 

Please can you provide a binary compiled with the latest version of Xcode 9.3 for carthage ?

Thanks

**Comment by freak4pc** [comment]
Hey @Aurazion - Most libraries usually don't provide compatibility until a GM is released, since it creates too much work for the authors to follow beta releases. 

Once the GM is released, all libraries in RxSwiftCommunity usually align accordingly.

Thanks for posting the issue !

**Comment by Aurazion** [comment]
Ok I understand, thanks for the very fast answer !

**Comment by Aurazion** [comment]
Hello @freak4pc 
Is it possible to update for Swift 4.1 ? Xcode 9.3 is now released.

Thanks !

**Comment by freak4pc** [comment]
Hey @Aurazion :) If you'd like to push out a PR I'd love to review it. Otherwise It'll have to wait for someone from the community to have time to do it which should be rather soon IMO :)

**Comment by Aurazion** [comment]
Yes I'll find a solution, thanks !

**Comment by freak4pc** [comment]
@Aurazion - You can use the fix from the second issue you commented on, if you'd like.
