### ISSUE TITLE
Swift4.1 support

### ISSUE THREAD

**Issue by noppefoxwolf** [RxSwiftCommunity/RxKeyboard#61]

**Comment by noppefoxwolf** [comment]
I builded latest commit.

swift 4.1 (902.0.48)
https://github.com/noppefoxwolf/RxKeyboard/releases

**Comment by Aurazion** [comment]
Thanks for the fork.
I hope the developer release his own build.

**Comment by freak4pc** [comment]
@noppefoxwolf Pushing your changes as a PR would be much more beneficial than building a separate fork :)

**Comment by freak4pc** [comment]
Oh I understand what you're saying :) OK.

**Comment by mendesbarreto** [comment]
Hey @freak4pc, what do you think of my PR, worth it?

**Comment by freak4pc** [comment]
Hey @mendesbarreto - No need to ping individual contributors :) When one of the contributors have time they usually review PRs. Also, since this is sort of @devxoul's library, I prefer him to review #62 .

**Comment by freak4pc** [comment]
Fixed in #62
