### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by Axadiw** [RxSwiftCommunity/RxKeyboard#68]
RxKeybaord doesn't compile on newest Xcode 10 beta

Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2 (swiftlang-1000.0.32.1 clang-1000.10.39).

**Comment by freak4pc** [comment]
Well, that makes sense given Xcode 10 is still in beta :) 
I imagine @devxoul will release a new binary when GM is out.

**Comment by wanbok** [comment]
I try to resolve it at #69

**Comment by RafaelPlantard** [comment]
Any news?

**Comment by freak4pc** [comment]
@RafaelPlantard Are you using CocoaPods? If so, can you try pointing directly to the master branch? Seems like #69 was merged to fix these issues.

**Comment by RafaelPlantard** [comment]
I'm using Carthage, just for while I create a fork of it, and release a new .zip to get from Carthage

**Comment by freak4pc** [comment]
Carthage release is up - CocoaPods gonna be up in probably a day or two (need to get some permission issue fixed).
