### ISSUE TITLE
[Proposal] Abolition of provision of binary

### ISSUE THREAD

**Issue by noppefoxwolf** [RxSwiftCommunity/RxKeyboard#71]
Providing binary will certainly speed up the installation.
However, we need to wait for binary to be provided each time.

https://github.com/RxSwiftCommunity/RxKeyboard/issues/68
https://github.com/RxSwiftCommunity/RxKeyboard/issues/66

When Swift 5 is released, ABI solves this problem.
Until then, I think that it is better not to provide the binary but to build it on each machine.

like this PR
https://github.com/RxSwiftCommunity/RxKeyboard/pull/43

**Comment by freak4pc** [comment]
I think the value of using a binary is too great to entirely get rid of. 
In essence, if the binary is invalid, you will get a re-compilation anyways - so I'm not sure why bother with abolition, as you suggest. 

Here's an example:
```
***  Skipped installing realm-cocoa.framework binary due to the error:
    "Incompatible Swift version - framework was built with 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)."
    Falling back to building from the source
```

**Comment by freak4pc** [comment]
Closing for now. If you have additional questions, please let me know and I'll reopen.
