### ISSUE TITLE
Cathage Build Failed

### ISSUE THREAD

**Issue by gordoneliel** [RxSwiftCommunity/RxKeyboard#75]
Building the framework throws the following error:
Incompatible Swift version - framework was built with 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2) and the local version is 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1).

Which is weird because the project is updated to Swift 4.2

**Comment by mgaines33** [comment]
It is still saying that it is built with swift 4.0.3.

**Comment by freak4pc** [comment]
Did you do a carthage update ? Try removing your Carthage folder and re-bootstrap.

**Comment by mgaines33** [comment]
cart file.resolved is showing>
binary "https://raw.githubusercontent.com/RxSwiftCommunity/RxKeyboard/master/RxKeyboard.json" "0.9.0"

**Comment by yurimingo** [comment]
@mgaines33 
did you try this? -> <https://stackoverflow.com/questions/45504896/how-to-clear-carthage-cache>
your carthage may reference previous RxKeyboard-v0.9.0.
i've solved same issue in this way.

**Comment by mgaines33** [comment]
@yurimingo That worked for me.  Thankyou.

**Comment by freak4pc** [comment]
Please see @yurimingo solution if you have a broken version in your Carthage cache.
