### ISSUE TITLE
Xcode 10 build fail

### ISSUE THREAD

**Issue by jerzykiler** [RxSwiftCommunity/RxKeyboard#76]
I am trying to build my project using Xcode 10 and swift 4.2 with `iOS Deployment Target` set to `iOS 10.0`.

I got RxKeyboard at version 0.9.0 using Carthage.

This is the error message I get at the 
`import RxKeyboard` line when I try to build for simulator:

`Module file's minimum deployment target is ios12.0 v12.0: /Users/<my_username>/<my_folder>/<my_project>/Carthage/Build/iOS/RxKeyboard.framework/Modules/RxKeyboard.swiftmodule/x86_64.swiftmodule`

and this is the error message I get when I try to build for iPhone X real device:

`Module file's minimum deployment target is ios12.0 v12.0: /Users/<my_username>/<my_folder>/<my_project>/Carthage/Build/iOS/RxKeyboard.framework/Modules/RxKeyboard.swiftmodule/arm64.swiftmodule`

Does that mean I cannot use this lib if I want to support iOS 10.0 ?

**Comment by yueno12** [comment]
+1

**Comment by mgaines33** [comment]
+2

**Comment by vaderdan** [comment]
Is it possible this issue to be related to
https://github.com/RxSwiftCommunity/RxKeyboard/pull/73/files#diff-354f30a63fb0907d4ad57269548329e3R10

I think that this is the source of the issue because previous version was running with 11 ios support
how are you building the framework just lame question 😄

**Comment by borg666** [comment]
any workaround about this?

**Comment by gustavopriebe** [comment]
I've set the minimum deployment target for iOS8.0 and created support for Carthage. Feel free to use the project at this link
https://github.com/gustavopriebe/RxKeyboard

or directly in Cartfile:

github "gustavopriebe/RxKeyboard" "master"

**Comment by KangTaeHoon** [comment]
@gustavopriebe 

Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/MyName/Desktop/MyProject/Carthage/Checkouts/RxKeyboard/RxKeyboard.xcodeproj -scheme RxKeyboard_iOS -configuration Release -derivedDataPath /Users/MyName/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/RxKeyboard/cf62c6d4c191ba680f31ce23c52641c88208136f -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/l_/xrm2b24d7ql58_b3kpxtmqs80000gn/T/RxKeyboard SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/MyName/Desktop/MyProject/Carthage/Checkouts/RxKeyboard)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/l_/xrm2b24d7ql58_b3kpxtmqs80000gn/T/carthage-xcodebuild.SuEnce.log

---> I downloaded direct by Cartfile but it happened like this error. What should I do? Could you explain how to solve this problem?

**Comment by freak4pc** [comment]
@devxoul Can you help out here? I really don't know your SPM-based release process that well. Would appreciate your assistance and might also be good to document this for others. Thanks !

**Comment by freak4pc** [comment]
@devxoul just released RxKeyboard 0.9.1. I tested on my own project with 8.0 deployment and the error is gone, so I'm closing this one. Please comment if you're still having issues!
