### ISSUE TITLE
Runtime error has occurred in binary downloaded using carthage.

### ISSUE THREAD

**Issue by yurimingo** [RxSwiftCommunity/RxKeyboard#77]
I tried to run a application then I got a following error message.
> dyld: Library not loaded: @rpath/RxCocoaRuntime.framework/RxCocoaRuntime
  Referenced from: /Users/yuri/Library/Developer/CoreSimulator/Devices/~~~/Yuri.app/Frameworks/RxKeyboard.framework/RxKeyboard
  Reason: image not found

It seems RxKeyboard refers RxCocoaRuntime.

**Comment by freak4pc** [comment]
It should refer to RxCocoa so that isn’t the issue. Can you try on a clean project ?

**Comment by yurimingo** [comment]
I tried again but it doesn't work.

In my understanding, carthage doesn't have `RxCocoaRuntime.framework` because It's included in `RxCocoa.framework`.
This is a similar issue to "<https://github.com/ReactorKit/ReactorKit/issues/17#issuecomment-305109741>".

I think TravisCI is supposed to remove `RxCocoaRuntime.framework` because `.travis.yml` in this project says that. <https://github.com/RxSwiftCommunity/RxKeyboard/blob/c06da88864e9281225ee5965c80b70e3a4125918/.travis.yml#L53>

**Comment by freak4pc** [comment]
@yurimingo Could you please try RxKeyboard 0.9.1 that was just released?

**Comment by yurimingo** [comment]
Thank you for the updates.
but i could not find 0.9.1 in https://raw.githubusercontent.com/RxSwiftCommunity/RxKeyboard/master/RxKeyboard.json .
so could you please update this file?

**Comment by freak4pc** [comment]
Updated. Let me know if it looks better now.

**Comment by yurimingo** [comment]
It works!
Thank you for your prompt reply!
